# RAVERSE MCP Proxy - Cloudflare Worker Configuration
#
# This configuration deploys the RAVERSE MCP proxy to Cloudflare Workers.
# The proxy provides edge caching and request routing to the RAVERSE backend.

name = "raverse-mcp-proxy"
main = "index.js"
compatibility_date = "2025-10-29"
compatibility_flags = ["nodejs_compat"]

# Workers deployment settings
workers_dev = true

# Build configuration
[build]
command = "npm install"
cwd = "./"

# Observability
[observability]
enabled = true

